### ISSUE TITLE
Asking permission to contribute

### ISSUE THREAD

**Issue by ghost** [shweshi/notepad#15]
after exploring your repo and website, i wanted  to contribute on your nav bar of your project by giving them a decent border with appreciable colors,size,padding,margin and many more intersting things to button' icons and on different section of your project ?
so i need your permission for that can i contribute?

**Comment by shweshi** [comment]
@Ashish9836 sure, contributions are welcome and will be credited.

**Comment by shweshi** [comment]
@Ashish9836 sure, contributions are welcome and will be credited.

**Comment by shweshi** [comment]
closed by #17
