### ISSUE TITLE
Wanted to Preform some tweaks on The Frontend UI and add some new features...

### ISSUE THREAD

**Issue by gajendra0180** [shweshi/notepad#16]
Hello Sir, I found your project quite interesting and would like to contribute to it. I would like to perform some tweaks on the UI and  also add some new features like font styling, word counter and so on. Can I have your permission to contribute?

**Comment by shweshi** [comment]
@gajendrahitz sure, go ahead.

**Comment by shweshi** [comment]
closed by #17
